# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ApplicationGatewayPrivateEndpointConnectionListResult
Response for ListApplicationGatewayPrivateEndpointConnection API service call. Gets all private endpoint connections for an application gateway.

    ApplicationGatewayPrivateEndpointConnectionListResult(;
        value=nothing,
        nextLink=nothing,
    )

    - value::Vector{ApplicationGatewayPrivateEndpointConnection} : List of private endpoint connections on an application gateway.
    - nextLink::String : URL to get the next set of results.
"""
Base.@kwdef mutable struct ApplicationGatewayPrivateEndpointConnectionListResult <: OpenAPI.APIModel
    value::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ApplicationGatewayPrivateEndpointConnection} }
    nextLink::Union{Nothing, String} = nothing

    function ApplicationGatewayPrivateEndpointConnectionListResult(value, nextLink, )
        o = new(value, nextLink, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ApplicationGatewayPrivateEndpointConnectionListResult

const _property_types_ApplicationGatewayPrivateEndpointConnectionListResult = Dict{Symbol,String}(Symbol("value")=>"Vector{ApplicationGatewayPrivateEndpointConnection}", Symbol("nextLink")=>"String", )
OpenAPI.property_type(::Type{ ApplicationGatewayPrivateEndpointConnectionListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ApplicationGatewayPrivateEndpointConnectionListResult[name]))}

function OpenAPI.check_required(o::ApplicationGatewayPrivateEndpointConnectionListResult)
    true
end

function OpenAPI.validate_properties(o::ApplicationGatewayPrivateEndpointConnectionListResult)
    OpenAPI.validate_property(ApplicationGatewayPrivateEndpointConnectionListResult, Symbol("value"), o.value)
    OpenAPI.validate_property(ApplicationGatewayPrivateEndpointConnectionListResult, Symbol("nextLink"), o.nextLink)
end

function OpenAPI.validate_property(::Type{ ApplicationGatewayPrivateEndpointConnectionListResult }, name::Symbol, val)


end
