# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ApplicationGatewayListResult
Response for ListApplicationGateways API service call.

    ApplicationGatewayListResult(;
        value=nothing,
        nextLink=nothing,
    )

    - value::Vector{ApplicationGateway} : List of an application gateways in a resource group.
    - nextLink::String : URL to get the next set of results.
"""
Base.@kwdef mutable struct ApplicationGatewayListResult <: OpenAPI.APIModel
    value::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ApplicationGateway} }
    nextLink::Union{Nothing, String} = nothing

    function ApplicationGatewayListResult(value, nextLink, )
        o = new(value, nextLink, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ApplicationGatewayListResult

const _property_types_ApplicationGatewayListResult = Dict{Symbol,String}(Symbol("value")=>"Vector{ApplicationGateway}", Symbol("nextLink")=>"String", )
OpenAPI.property_type(::Type{ ApplicationGatewayListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ApplicationGatewayListResult[name]))}

function OpenAPI.check_required(o::ApplicationGatewayListResult)
    true
end

function OpenAPI.validate_properties(o::ApplicationGatewayListResult)
    OpenAPI.validate_property(ApplicationGatewayListResult, Symbol("value"), o.value)
    OpenAPI.validate_property(ApplicationGatewayListResult, Symbol("nextLink"), o.nextLink)
end

function OpenAPI.validate_property(::Type{ ApplicationGatewayListResult }, name::Symbol, val)


end
