# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ApplicationGatewaySslProfile
SSL profile of an application gateway.

    ApplicationGatewaySslProfile(;
        properties=nothing,
        name=nothing,
        etag=nothing,
        type=nothing,
        id=nothing,
    )

    - properties::ApplicationGatewaySslProfilePropertiesFormat
    - name::String : Name of the SSL profile that is unique within an Application Gateway.
    - etag::String : A unique read-only string that changes whenever the resource is updated.
    - type::String : Type of the resource.
    - id::String : Resource ID.
"""
Base.@kwdef mutable struct ApplicationGatewaySslProfile <: OpenAPI.APIModel
    properties = nothing # spec type: Union{ Nothing, ApplicationGatewaySslProfilePropertiesFormat }
    name::Union{Nothing, String} = nothing
    etag::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing
    id::Union{Nothing, String} = nothing

    function ApplicationGatewaySslProfile(properties, name, etag, type, id, )
        o = new(properties, name, etag, type, id, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ApplicationGatewaySslProfile

const _property_types_ApplicationGatewaySslProfile = Dict{Symbol,String}(Symbol("properties")=>"ApplicationGatewaySslProfilePropertiesFormat", Symbol("name")=>"String", Symbol("etag")=>"String", Symbol("type")=>"String", Symbol("id")=>"String", )
OpenAPI.property_type(::Type{ ApplicationGatewaySslProfile }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ApplicationGatewaySslProfile[name]))}

function OpenAPI.check_required(o::ApplicationGatewaySslProfile)
    true
end

function OpenAPI.validate_properties(o::ApplicationGatewaySslProfile)
    OpenAPI.validate_property(ApplicationGatewaySslProfile, Symbol("properties"), o.properties)
    OpenAPI.validate_property(ApplicationGatewaySslProfile, Symbol("name"), o.name)
    OpenAPI.validate_property(ApplicationGatewaySslProfile, Symbol("etag"), o.etag)
    OpenAPI.validate_property(ApplicationGatewaySslProfile, Symbol("type"), o.type)
    OpenAPI.validate_property(ApplicationGatewaySslProfile, Symbol("id"), o.id)
end

function OpenAPI.validate_property(::Type{ ApplicationGatewaySslProfile }, name::Symbol, val)





end
