# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ApplicationGatewayBackendAddressPool_2
Backend Address Pool of an application gateway.

    ApplicationGatewayBackendAddressPool2(;
        properties=nothing,
        name=nothing,
        etag=nothing,
        type=nothing,
        id=nothing,
    )

    - properties::ApplicationGatewayBackendAddressPoolPropertiesFormat2
    - name::String : Name of the backend address pool that is unique within an Application Gateway.
    - etag::String : A unique read-only string that changes whenever the resource is updated.
    - type::String : Type of the resource.
    - id::String : Resource ID.
"""
Base.@kwdef mutable struct ApplicationGatewayBackendAddressPool2 <: OpenAPI.APIModel
    properties = nothing # spec type: Union{ Nothing, ApplicationGatewayBackendAddressPoolPropertiesFormat2 }
    name::Union{Nothing, String} = nothing
    etag::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing
    id::Union{Nothing, String} = nothing

    function ApplicationGatewayBackendAddressPool2(properties, name, etag, type, id, )
        OpenAPI.validate_property(ApplicationGatewayBackendAddressPool2, Symbol("properties"), properties)
        OpenAPI.validate_property(ApplicationGatewayBackendAddressPool2, Symbol("name"), name)
        OpenAPI.validate_property(ApplicationGatewayBackendAddressPool2, Symbol("etag"), etag)
        OpenAPI.validate_property(ApplicationGatewayBackendAddressPool2, Symbol("type"), type)
        OpenAPI.validate_property(ApplicationGatewayBackendAddressPool2, Symbol("id"), id)
        return new(properties, name, etag, type, id, )
    end
end # type ApplicationGatewayBackendAddressPool2

const _property_types_ApplicationGatewayBackendAddressPool2 = Dict{Symbol,String}(Symbol("properties")=>"ApplicationGatewayBackendAddressPoolPropertiesFormat2", Symbol("name")=>"String", Symbol("etag")=>"String", Symbol("type")=>"String", Symbol("id")=>"String", )
OpenAPI.property_type(::Type{ ApplicationGatewayBackendAddressPool2 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ApplicationGatewayBackendAddressPool2[name]))}

function check_required(o::ApplicationGatewayBackendAddressPool2)
    true
end

function OpenAPI.validate_property(::Type{ ApplicationGatewayBackendAddressPool2 }, name::Symbol, val)
end
