# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ApplicationGateway
Application gateway resource.

    ApplicationGateway(;
        properties=nothing,
        etag=nothing,
        zones=nothing,
        identity=nothing,
        id=nothing,
        name=nothing,
        type=nothing,
        location=nothing,
        tags=nothing,
    )

    - properties::ApplicationGatewayPropertiesFormat
    - etag::String : A unique read-only string that changes whenever the resource is updated.
    - zones::Vector{String} : A list of availability zones denoting where the resource needs to come from.
    - identity::ManagedServiceIdentity
    - id::String : Resource ID.
    - name::String : Resource name.
    - type::String : Resource type.
    - location::String : Resource location.
    - tags::Dict{String, String} : Resource tags.
"""
Base.@kwdef mutable struct ApplicationGateway <: OpenAPI.APIModel
    properties = nothing # spec type: Union{ Nothing, ApplicationGatewayPropertiesFormat }
    etag::Union{Nothing, String} = nothing
    zones::Union{Nothing, Vector{String}} = nothing
    identity = nothing # spec type: Union{ Nothing, ManagedServiceIdentity }
    id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing
    location::Union{Nothing, String} = nothing
    tags::Union{Nothing, Dict{String, String}} = nothing

    function ApplicationGateway(properties, etag, zones, identity, id, name, type, location, tags, )
        o = new(properties, etag, zones, identity, id, name, type, location, tags, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ApplicationGateway

const _property_types_ApplicationGateway = Dict{Symbol,String}(Symbol("properties")=>"ApplicationGatewayPropertiesFormat", Symbol("etag")=>"String", Symbol("zones")=>"Vector{String}", Symbol("identity")=>"ManagedServiceIdentity", Symbol("id")=>"String", Symbol("name")=>"String", Symbol("type")=>"String", Symbol("location")=>"String", Symbol("tags")=>"Dict{String, String}", )
OpenAPI.property_type(::Type{ ApplicationGateway }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ApplicationGateway[name]))}

function OpenAPI.check_required(o::ApplicationGateway)
    true
end

function OpenAPI.validate_properties(o::ApplicationGateway)
    OpenAPI.validate_property(ApplicationGateway, Symbol("properties"), o.properties)
    OpenAPI.validate_property(ApplicationGateway, Symbol("etag"), o.etag)
    OpenAPI.validate_property(ApplicationGateway, Symbol("zones"), o.zones)
    OpenAPI.validate_property(ApplicationGateway, Symbol("identity"), o.identity)
    OpenAPI.validate_property(ApplicationGateway, Symbol("id"), o.id)
    OpenAPI.validate_property(ApplicationGateway, Symbol("name"), o.name)
    OpenAPI.validate_property(ApplicationGateway, Symbol("type"), o.type)
    OpenAPI.validate_property(ApplicationGateway, Symbol("location"), o.location)
    OpenAPI.validate_property(ApplicationGateway, Symbol("tags"), o.tags)
end

function OpenAPI.validate_property(::Type{ ApplicationGateway }, name::Symbol, val)









end
