# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ApplicationGatewayProbe
Probe of the application gateway.

    ApplicationGatewayProbe(;
        properties=nothing,
        name=nothing,
        etag=nothing,
        type=nothing,
        id=nothing,
    )

    - properties::ApplicationGatewayProbePropertiesFormat
    - name::String : Name of the probe that is unique within an Application Gateway.
    - etag::String : A unique read-only string that changes whenever the resource is updated.
    - type::String : Type of the resource.
    - id::String : Resource ID.
"""
Base.@kwdef mutable struct ApplicationGatewayProbe <: OpenAPI.APIModel
    properties = nothing # spec type: Union{ Nothing, ApplicationGatewayProbePropertiesFormat }
    name::Union{Nothing, String} = nothing
    etag::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing
    id::Union{Nothing, String} = nothing

    function ApplicationGatewayProbe(properties, name, etag, type, id, )
        o = new(properties, name, etag, type, id, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ApplicationGatewayProbe

const _property_types_ApplicationGatewayProbe = Dict{Symbol,String}(Symbol("properties")=>"ApplicationGatewayProbePropertiesFormat", Symbol("name")=>"String", Symbol("etag")=>"String", Symbol("type")=>"String", Symbol("id")=>"String", )
OpenAPI.property_type(::Type{ ApplicationGatewayProbe }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ApplicationGatewayProbe[name]))}

function OpenAPI.check_required(o::ApplicationGatewayProbe)
    true
end

function OpenAPI.validate_properties(o::ApplicationGatewayProbe)
    OpenAPI.validate_property(ApplicationGatewayProbe, Symbol("properties"), o.properties)
    OpenAPI.validate_property(ApplicationGatewayProbe, Symbol("name"), o.name)
    OpenAPI.validate_property(ApplicationGatewayProbe, Symbol("etag"), o.etag)
    OpenAPI.validate_property(ApplicationGatewayProbe, Symbol("type"), o.type)
    OpenAPI.validate_property(ApplicationGatewayProbe, Symbol("id"), o.id)
end

function OpenAPI.validate_property(::Type{ ApplicationGatewayProbe }, name::Symbol, val)





end
