# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""VirtualNetworkGatewayConnectionStatus
Virtual Network Gateway connection status.

    VirtualNetworkGatewayConnectionStatus(;
    )

"""
Base.@kwdef mutable struct VirtualNetworkGatewayConnectionStatus <: OpenAPI.APIModel

    function VirtualNetworkGatewayConnectionStatus()
        return new()
    end
end # type VirtualNetworkGatewayConnectionStatus

const _property_types_VirtualNetworkGatewayConnectionStatus = Dict{Symbol,String}()
OpenAPI.property_type(::Type{ VirtualNetworkGatewayConnectionStatus }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_VirtualNetworkGatewayConnectionStatus[name]))}

function check_required(o::VirtualNetworkGatewayConnectionStatus)
    true
end

function OpenAPI.validate_property(::Type{ VirtualNetworkGatewayConnectionStatus }, name::Symbol, val)
end
