# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""VirtualNetworkConnectionGatewayReference
A reference to VirtualNetworkGateway or LocalNetworkGateway resource.

    VirtualNetworkConnectionGatewayReference(;
        id=nothing,
    )

    - id::String : The ID of VirtualNetworkGateway or LocalNetworkGateway resource.
"""
Base.@kwdef mutable struct VirtualNetworkConnectionGatewayReference <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing

    function VirtualNetworkConnectionGatewayReference(id, )
        OpenAPI.validate_property(VirtualNetworkConnectionGatewayReference, Symbol("id"), id)
        return new(id, )
    end
end # type VirtualNetworkConnectionGatewayReference

const _property_types_VirtualNetworkConnectionGatewayReference = Dict{Symbol,String}(Symbol("id")=>"String", )
OpenAPI.property_type(::Type{ VirtualNetworkConnectionGatewayReference }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_VirtualNetworkConnectionGatewayReference[name]))}

function check_required(o::VirtualNetworkConnectionGatewayReference)
    o.id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ VirtualNetworkConnectionGatewayReference }, name::Symbol, val)
end
