# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ExpressRouteFailoverConnectionResourceDetails

    ExpressRouteFailoverConnectionResourceDetails(;
        nrpResourceUri=nothing,
        name=nothing,
        status=nothing,
        lastUpdatedTime=nothing,
    )

    - nrpResourceUri::String : NRP Resource URI of the connection
    - name::String : Connection Name
    - status::String : The current status of the connection
    - lastUpdatedTime::String : Time when the connection was last updated
"""
Base.@kwdef mutable struct ExpressRouteFailoverConnectionResourceDetails <: OpenAPI.APIModel
    nrpResourceUri::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    status::Union{Nothing, String} = nothing
    lastUpdatedTime::Union{Nothing, String} = nothing

    function ExpressRouteFailoverConnectionResourceDetails(nrpResourceUri, name, status, lastUpdatedTime, )
        o = new(nrpResourceUri, name, status, lastUpdatedTime, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ExpressRouteFailoverConnectionResourceDetails

const _property_types_ExpressRouteFailoverConnectionResourceDetails = Dict{Symbol,String}(Symbol("nrpResourceUri")=>"String", Symbol("name")=>"String", Symbol("status")=>"String", Symbol("lastUpdatedTime")=>"String", )
OpenAPI.property_type(::Type{ ExpressRouteFailoverConnectionResourceDetails }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ExpressRouteFailoverConnectionResourceDetails[name]))}

function OpenAPI.check_required(o::ExpressRouteFailoverConnectionResourceDetails)
    true
end

function OpenAPI.validate_properties(o::ExpressRouteFailoverConnectionResourceDetails)
    OpenAPI.validate_property(ExpressRouteFailoverConnectionResourceDetails, Symbol("nrpResourceUri"), o.nrpResourceUri)
    OpenAPI.validate_property(ExpressRouteFailoverConnectionResourceDetails, Symbol("name"), o.name)
    OpenAPI.validate_property(ExpressRouteFailoverConnectionResourceDetails, Symbol("status"), o.status)
    OpenAPI.validate_property(ExpressRouteFailoverConnectionResourceDetails, Symbol("lastUpdatedTime"), o.lastUpdatedTime)
end

function OpenAPI.validate_property(::Type{ ExpressRouteFailoverConnectionResourceDetails }, name::Symbol, val)

    if name === Symbol("nrpResourceUri")
        OpenAPI.validate_param(name, "ExpressRouteFailoverConnectionResourceDetails", :format, val, "arm-id")
    end


    if name === Symbol("status")
        OpenAPI.validate_param(name, "ExpressRouteFailoverConnectionResourceDetails", :enum, val, ["Connected", "Disconnected"])
    end


end
