# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct ConnectionMonitorWorkspaceSettings <: SwaggerModel
    workspaceResourceId::Any # spec type: Union{ Nothing, String } # spec name: workspaceResourceId

    function ConnectionMonitorWorkspaceSettings(;workspaceResourceId=nothing)
        o = new()
        validate_property(ConnectionMonitorWorkspaceSettings, Symbol("workspaceResourceId"), workspaceResourceId)
        setfield!(o, Symbol("workspaceResourceId"), workspaceResourceId)
        o
    end
end # type ConnectionMonitorWorkspaceSettings

const _property_map_ConnectionMonitorWorkspaceSettings = Dict{Symbol,Symbol}(Symbol("workspaceResourceId")=>Symbol("workspaceResourceId"))
const _property_types_ConnectionMonitorWorkspaceSettings = Dict{Symbol,String}(Symbol("workspaceResourceId")=>"String")
Base.propertynames(::Type{ ConnectionMonitorWorkspaceSettings }) = collect(keys(_property_map_ConnectionMonitorWorkspaceSettings))
Swagger.property_type(::Type{ ConnectionMonitorWorkspaceSettings }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ConnectionMonitorWorkspaceSettings[name]))}
Swagger.field_name(::Type{ ConnectionMonitorWorkspaceSettings }, property_name::Symbol) =  _property_map_ConnectionMonitorWorkspaceSettings[property_name]

function check_required(o::ConnectionMonitorWorkspaceSettings)
    true
end

function validate_property(::Type{ ConnectionMonitorWorkspaceSettings }, name::Symbol, val)
end
