# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PacketCaptureListResult
List of packet capture sessions.

    PacketCaptureListResult(;
        value=nothing,
    )

    - value::Vector{PacketCaptureResult} : Information about packet capture sessions.
"""
Base.@kwdef mutable struct PacketCaptureListResult <: OpenAPI.APIModel
    value::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PacketCaptureResult} }

    function PacketCaptureListResult(value, )
        o = new(value, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PacketCaptureListResult

const _property_types_PacketCaptureListResult = Dict{Symbol,String}(Symbol("value")=>"Vector{PacketCaptureResult}", )
OpenAPI.property_type(::Type{ PacketCaptureListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PacketCaptureListResult[name]))}

function OpenAPI.check_required(o::PacketCaptureListResult)
    true
end

function OpenAPI.validate_properties(o::PacketCaptureListResult)
    OpenAPI.validate_property(PacketCaptureListResult, Symbol("value"), o.value)
end

function OpenAPI.validate_property(::Type{ PacketCaptureListResult }, name::Symbol, val)

end
