# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ConnectionMonitorDestination
Describes the destination of connection monitor.

    ConnectionMonitorDestination(;
        resourceId=nothing,
        address=nothing,
        port=nothing,
    )

    - resourceId::String : The ID of the resource used as the destination by connection monitor.
    - address::String : Address of the connection monitor destination (IP or domain name).
    - port::Int64 : The destination port used by connection monitor.
"""
Base.@kwdef mutable struct ConnectionMonitorDestination <: OpenAPI.APIModel
    resourceId::Union{Nothing, String} = nothing
    address::Union{Nothing, String} = nothing
    port::Union{Nothing, Int64} = nothing

    function ConnectionMonitorDestination(resourceId, address, port, )
        OpenAPI.validate_property(ConnectionMonitorDestination, Symbol("resourceId"), resourceId)
        OpenAPI.validate_property(ConnectionMonitorDestination, Symbol("address"), address)
        OpenAPI.validate_property(ConnectionMonitorDestination, Symbol("port"), port)
        return new(resourceId, address, port, )
    end
end # type ConnectionMonitorDestination

const _property_types_ConnectionMonitorDestination = Dict{Symbol,String}(Symbol("resourceId")=>"String", Symbol("address")=>"String", Symbol("port")=>"Int64", )
OpenAPI.property_type(::Type{ ConnectionMonitorDestination }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ConnectionMonitorDestination[name]))}

function check_required(o::ConnectionMonitorDestination)
    true
end

function OpenAPI.validate_property(::Type{ ConnectionMonitorDestination }, name::Symbol, val)
end
