# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ConnectionMonitorParameters
Parameters that define the operation to create a connection monitor.

    ConnectionMonitorParameters(;
        source=nothing,
        destination=nothing,
        autoStart=true,
        monitoringIntervalInSeconds=60,
        endpoints=nothing,
        testConfigurations=nothing,
        testGroups=nothing,
        outputs=nothing,
        notes=nothing,
    )

    - source::ConnectionMonitorSource
    - destination::ConnectionMonitorDestination
    - autoStart::Bool : Determines if the connection monitor will start automatically once created.
    - monitoringIntervalInSeconds::Int64 : Monitoring interval in seconds.
    - endpoints::Vector{ConnectionMonitorEndpoint} : List of connection monitor endpoints.
    - testConfigurations::Vector{ConnectionMonitorTestConfiguration} : List of connection monitor test configurations.
    - testGroups::Vector{ConnectionMonitorTestGroup} : List of connection monitor test groups.
    - outputs::Vector{ConnectionMonitorOutput} : List of connection monitor outputs.
    - notes::String : Optional notes to be associated with the connection monitor.
"""
Base.@kwdef mutable struct ConnectionMonitorParameters <: OpenAPI.APIModel
    source = nothing # spec type: Union{ Nothing, ConnectionMonitorSource }
    destination = nothing # spec type: Union{ Nothing, ConnectionMonitorDestination }
    autoStart::Union{Nothing, Bool} = true
    monitoringIntervalInSeconds::Union{Nothing, Int64} = 60
    endpoints::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ConnectionMonitorEndpoint} }
    testConfigurations::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ConnectionMonitorTestConfiguration} }
    testGroups::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ConnectionMonitorTestGroup} }
    outputs::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ConnectionMonitorOutput} }
    notes::Union{Nothing, String} = nothing

    function ConnectionMonitorParameters(source, destination, autoStart, monitoringIntervalInSeconds, endpoints, testConfigurations, testGroups, outputs, notes, )
        o = new(source, destination, autoStart, monitoringIntervalInSeconds, endpoints, testConfigurations, testGroups, outputs, notes, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ConnectionMonitorParameters

const _property_types_ConnectionMonitorParameters = Dict{Symbol,String}(Symbol("source")=>"ConnectionMonitorSource", Symbol("destination")=>"ConnectionMonitorDestination", Symbol("autoStart")=>"Bool", Symbol("monitoringIntervalInSeconds")=>"Int64", Symbol("endpoints")=>"Vector{ConnectionMonitorEndpoint}", Symbol("testConfigurations")=>"Vector{ConnectionMonitorTestConfiguration}", Symbol("testGroups")=>"Vector{ConnectionMonitorTestGroup}", Symbol("outputs")=>"Vector{ConnectionMonitorOutput}", Symbol("notes")=>"String", )
OpenAPI.property_type(::Type{ ConnectionMonitorParameters }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ConnectionMonitorParameters[name]))}

function OpenAPI.check_required(o::ConnectionMonitorParameters)
    true
end

function OpenAPI.validate_properties(o::ConnectionMonitorParameters)
    OpenAPI.validate_property(ConnectionMonitorParameters, Symbol("source"), o.source)
    OpenAPI.validate_property(ConnectionMonitorParameters, Symbol("destination"), o.destination)
    OpenAPI.validate_property(ConnectionMonitorParameters, Symbol("autoStart"), o.autoStart)
    OpenAPI.validate_property(ConnectionMonitorParameters, Symbol("monitoringIntervalInSeconds"), o.monitoringIntervalInSeconds)
    OpenAPI.validate_property(ConnectionMonitorParameters, Symbol("endpoints"), o.endpoints)
    OpenAPI.validate_property(ConnectionMonitorParameters, Symbol("testConfigurations"), o.testConfigurations)
    OpenAPI.validate_property(ConnectionMonitorParameters, Symbol("testGroups"), o.testGroups)
    OpenAPI.validate_property(ConnectionMonitorParameters, Symbol("outputs"), o.outputs)
    OpenAPI.validate_property(ConnectionMonitorParameters, Symbol("notes"), o.notes)
end

function OpenAPI.validate_property(::Type{ ConnectionMonitorParameters }, name::Symbol, val)




    if name === Symbol("monitoringIntervalInSeconds")
        OpenAPI.validate_param(name, "ConnectionMonitorParameters", :format, val, "int32")
    end
    if name === Symbol("monitoringIntervalInSeconds")
        OpenAPI.validate_param(name, "ConnectionMonitorParameters", :maximum, val, 1800, false)
        OpenAPI.validate_param(name, "ConnectionMonitorParameters", :minimum, val, 30, false)
    end





end
