# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

module SubscriptionClient

using Random
using Dates
using HTTP
using Swagger
import Swagger: set_field!, get_field, isset_field, validate_field, SwaggerApi, SwaggerModel
import Base: convert

include("modelincludes.jl")

include("api_SubscriptionsApi.jl")
include("api_TenantsApi.jl")

# export models
export convert, Location
export convert, LocationListResult
export convert, Subscription
export convert, SubscriptionListResult
export convert, SubscriptionPolicies
export convert, TenantIdDescription
export convert, TenantListResult

# export operations
export convert, SubscriptionsApi, TenantsApi

export check_required, set_field!, get_field, isset_field, convert

end
