include("model_PublicIPAddress.jl")
include("model_IPConfiguration.jl")
include("model_PublicIPAddressDnsSettings.jl")
include("model_PublicIPAddressPropertiesFormat.jl")
include("model_PublicIPAddressListResult.jl")
include("model_Resource.jl")
