# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""InboundNatRuleListResult
Response for ListInboundNatRule API service call.

    InboundNatRuleListResult(;
        value=nothing,
        nextLink=nothing,
    )

    - value::Vector{InboundNatRule} : A list of inbound nat rules in a load balancer.
    - nextLink::String : The URL to get the next set of results.
"""
Base.@kwdef mutable struct InboundNatRuleListResult <: OpenAPI.APIModel
    value::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{InboundNatRule} }
    nextLink::Union{Nothing, String} = nothing

    function InboundNatRuleListResult(value, nextLink, )
        OpenAPI.validate_property(InboundNatRuleListResult, Symbol("value"), value)
        OpenAPI.validate_property(InboundNatRuleListResult, Symbol("nextLink"), nextLink)
        return new(value, nextLink, )
    end
end # type InboundNatRuleListResult

const _property_types_InboundNatRuleListResult = Dict{Symbol,String}(Symbol("value")=>"Vector{InboundNatRule}", Symbol("nextLink")=>"String", )
OpenAPI.property_type(::Type{ InboundNatRuleListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_InboundNatRuleListResult[name]))}

function check_required(o::InboundNatRuleListResult)
    true
end

function OpenAPI.validate_property(::Type{ InboundNatRuleListResult }, name::Symbol, val)
end
