# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct ManagementPolicy <: SwaggerModel
    id::Any # spec type: Union{ Nothing, String } # spec name: id
    name::Any # spec type: Union{ Nothing, String } # spec name: name
    type::Any # spec type: Union{ Nothing, String } # spec name: type

    function ManagementPolicy(;id=nothing, name=nothing, type=nothing)
        o = new()
        validate_property(ManagementPolicy, Symbol("id"), id)
        setfield!(o, Symbol("id"), id)
        validate_property(ManagementPolicy, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        validate_property(ManagementPolicy, Symbol("type"), type)
        setfield!(o, Symbol("type"), type)
        o
    end
end # type ManagementPolicy

const _property_map_ManagementPolicy = Dict{Symbol,Symbol}(Symbol("id")=>Symbol("id"), Symbol("name")=>Symbol("name"), Symbol("type")=>Symbol("type"))
const _property_types_ManagementPolicy = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", Symbol("type")=>"String")
Base.propertynames(::Type{ ManagementPolicy }) = collect(keys(_property_map_ManagementPolicy))
Swagger.property_type(::Type{ ManagementPolicy }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ManagementPolicy[name]))}
Swagger.field_name(::Type{ ManagementPolicy }, property_name::Symbol) =  _property_map_ManagementPolicy[property_name]

function check_required(o::ManagementPolicy)
    true
end

function validate_property(::Type{ ManagementPolicy }, name::Symbol, val)
end
