# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type ExpressRouteCircuitPeering <: SwaggerModel
    id::Nullable{ String } # id

    function ExpressRouteCircuitPeering(;id=nothing)
        o = new()
        set_field!(o, :id, id)
        o
    end
end # type ExpressRouteCircuitPeering

const _name_map_ExpressRouteCircuitPeering = Dict{String,Symbol}(["id"=>:id])
const _field_map_ExpressRouteCircuitPeering = Dict{Symbol,String}([:id=>"id"])
Swagger.name_map(::Type{ ExpressRouteCircuitPeering }) = _name_map_ExpressRouteCircuitPeering
Swagger.field_map(::Type{ ExpressRouteCircuitPeering }) = _field_map_ExpressRouteCircuitPeering

function check_required(o::ExpressRouteCircuitPeering)
    true
end

function validate_field(o::ExpressRouteCircuitPeering, name::Symbol, val)
end
