# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct AdlsError <: SwaggerModel
    RemoteException::Any # spec type: Union{ Nothing, AdlsRemoteException } # spec name: RemoteException

    function AdlsError(;RemoteException=nothing)
        o = new()
        validate_property(AdlsError, Symbol("RemoteException"), RemoteException)
        setfield!(o, Symbol("RemoteException"), RemoteException)
        o
    end
end # type AdlsError

const _property_map_AdlsError = Dict{Symbol,Symbol}(Symbol("RemoteException")=>Symbol("RemoteException"))
const _property_types_AdlsError = Dict{Symbol,String}(Symbol("RemoteException")=>"AdlsRemoteException")
Base.propertynames(::Type{ AdlsError }) = collect(keys(_property_map_AdlsError))
Swagger.property_type(::Type{ AdlsError }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_AdlsError[name]))}
Swagger.field_name(::Type{ AdlsError }, property_name::Symbol) =  _property_map_AdlsError[property_name]

function check_required(o::AdlsError)
    true
end

function validate_property(::Type{ AdlsError }, name::Symbol, val)
end
