# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type AdlsUnsupportedOperationException <: SwaggerModel
    exception::Nullable{ String } # exception
    javaClassName::Nullable{ String } # javaClassName
    message::Nullable{ String } # message

    function AdlsUnsupportedOperationException(;exception=nothing, javaClassName=nothing, message=nothing)
        o = new()
        set_field!(o, :exception, exception)
        set_field!(o, :javaClassName, javaClassName)
        set_field!(o, :message, message)
        o
    end
end # type AdlsUnsupportedOperationException

const _name_map_AdlsUnsupportedOperationException = Dict{String,Symbol}(["exception"=>:exception, "javaClassName"=>:javaClassName, "message"=>:message])
const _field_map_AdlsUnsupportedOperationException = Dict{Symbol,String}([:exception=>"exception", :javaClassName=>"javaClassName", :message=>"message"])
Swagger.name_map(::Type{ AdlsUnsupportedOperationException }) = _name_map_AdlsUnsupportedOperationException
Swagger.field_map(::Type{ AdlsUnsupportedOperationException }) = _field_map_AdlsUnsupportedOperationException

function check_required(o::AdlsUnsupportedOperationException)
    isnull(o.exception) && (return false)
    true
end

function validate_field(o::AdlsUnsupportedOperationException, name::Symbol, val)
end
