# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct ContainerServiceServicePrincipalProfile <: SwaggerModel
    clientId::Union{ Nothing, String } # clientId
    secret::Union{ Nothing, String } # secret

    function ContainerServiceServicePrincipalProfile(;clientId=nothing, secret=nothing)
        o = new()
        set_field!(o, :clientId, clientId)
        set_field!(o, :secret, secret)
        o
    end
end # type ContainerServiceServicePrincipalProfile

const _name_map_ContainerServiceServicePrincipalProfile = Dict{String,Symbol}(["clientId"=>:clientId, "secret"=>:secret])
const _field_map_ContainerServiceServicePrincipalProfile = Dict{Symbol,String}([:clientId=>"clientId", :secret=>"secret"])
Swagger.name_map(::Type{ ContainerServiceServicePrincipalProfile }) = _name_map_ContainerServiceServicePrincipalProfile
Swagger.field_map(::Type{ ContainerServiceServicePrincipalProfile }) = _field_map_ContainerServiceServicePrincipalProfile

function check_required(o::ContainerServiceServicePrincipalProfile)
    (o.clientId === nothing) && (return false)
    (o.secret === nothing) && (return false)
    true
end

function validate_field(o::ContainerServiceServicePrincipalProfile, name::Symbol, val)
end
