# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ProviderListResult
List of resource providers.

    ProviderListResult(;
        value=nothing,
        nextLink=nothing,
    )

    - value::Vector{Provider} : An array of resource providers.
    - nextLink::String : The URL to use for getting the next set of results.
"""
Base.@kwdef mutable struct ProviderListResult <: OpenAPI.APIModel
    value::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Provider} }
    nextLink::Union{Nothing, String} = nothing

    function ProviderListResult(value, nextLink, )
        o = new(value, nextLink, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ProviderListResult

const _property_types_ProviderListResult = Dict{Symbol,String}(Symbol("value")=>"Vector{Provider}", Symbol("nextLink")=>"String", )
OpenAPI.property_type(::Type{ ProviderListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProviderListResult[name]))}

function OpenAPI.check_required(o::ProviderListResult)
    true
end

function OpenAPI.validate_properties(o::ProviderListResult)
    OpenAPI.validate_property(ProviderListResult, Symbol("value"), o.value)
    OpenAPI.validate_property(ProviderListResult, Symbol("nextLink"), o.nextLink)
end

function OpenAPI.validate_property(::Type{ ProviderListResult }, name::Symbol, val)


end
