# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type AccessUriOutput <: SwaggerModel
    output::Nullable{ AccessUriRaw } # output

    function AccessUriOutput(;output=nothing)
        o = new()
        set_field!(o, :output, output)
        o
    end
end # type AccessUriOutput

const _name_map_AccessUriOutput = Dict{String,Symbol}(["output"=>:output])
const _field_map_AccessUriOutput = Dict{Symbol,String}([:output=>"output"])
Swagger.name_map(::Type{ AccessUriOutput }) = _name_map_AccessUriOutput
Swagger.field_map(::Type{ AccessUriOutput }) = _field_map_AccessUriOutput

function check_required(o::AccessUriOutput)
    true
end

function validate_field(o::AccessUriOutput, name::Symbol, val)
end
