# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type KeyVaultAndSecretReference <: SwaggerModel
    sourceVault::Nullable{ SourceVault } # sourceVault
    secretUrl::Nullable{ String } # secretUrl

    function KeyVaultAndSecretReference(;sourceVault=nothing, secretUrl=nothing)
        o = new()
        set_field!(o, :sourceVault, sourceVault)
        set_field!(o, :secretUrl, secretUrl)
        o
    end
end # type KeyVaultAndSecretReference

const _name_map_KeyVaultAndSecretReference = Dict{String,Symbol}(["sourceVault"=>:sourceVault, "secretUrl"=>:secretUrl])
const _field_map_KeyVaultAndSecretReference = Dict{Symbol,String}([:sourceVault=>"sourceVault", :secretUrl=>"secretUrl"])
Swagger.name_map(::Type{ KeyVaultAndSecretReference }) = _name_map_KeyVaultAndSecretReference
Swagger.field_map(::Type{ KeyVaultAndSecretReference }) = _field_map_KeyVaultAndSecretReference

function check_required(o::KeyVaultAndSecretReference)
    isnull(o.sourceVault) && (return false)
    isnull(o.secretUrl) && (return false)
    true
end

function validate_field(o::KeyVaultAndSecretReference, name::Symbol, val)
end
