# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PairedRegion
Information regarding paired region.

    PairedRegion(;
        name=nothing,
        id=nothing,
        subscriptionId=nothing,
    )

    - name::String : The name of the paired region.
    - id::String : The fully qualified ID of the location. For example, /subscriptions/00000000-0000-0000-0000-000000000000/locations/westus.
    - subscriptionId::String : The subscription ID.
"""
Base.@kwdef mutable struct PairedRegion <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    id::Union{Nothing, String} = nothing
    subscriptionId::Union{Nothing, String} = nothing

    function PairedRegion(name, id, subscriptionId, )
        OpenAPI.validate_property(PairedRegion, Symbol("name"), name)
        OpenAPI.validate_property(PairedRegion, Symbol("id"), id)
        OpenAPI.validate_property(PairedRegion, Symbol("subscriptionId"), subscriptionId)
        return new(name, id, subscriptionId, )
    end
end # type PairedRegion

const _property_types_PairedRegion = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("id")=>"String", Symbol("subscriptionId")=>"String", )
OpenAPI.property_type(::Type{ PairedRegion }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PairedRegion[name]))}

function check_required(o::PairedRegion)
    true
end

function OpenAPI.validate_property(::Type{ PairedRegion }, name::Symbol, val)
end
