# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct SubnetListResult <: SwaggerModel
    value::Any # spec type: Union{ Nothing, Vector{Subnet} } # spec name: value
    nextLink::Any # spec type: Union{ Nothing, String } # spec name: nextLink

    function SubnetListResult(;value=nothing, nextLink=nothing)
        o = new()
        validate_property(SubnetListResult, Symbol("value"), value)
        setfield!(o, Symbol("value"), value)
        validate_property(SubnetListResult, Symbol("nextLink"), nextLink)
        setfield!(o, Symbol("nextLink"), nextLink)
        o
    end
end # type SubnetListResult

const _property_map_SubnetListResult = Dict{Symbol,Symbol}(Symbol("value")=>Symbol("value"), Symbol("nextLink")=>Symbol("nextLink"))
const _property_types_SubnetListResult = Dict{Symbol,String}(Symbol("value")=>"Vector{Subnet}", Symbol("nextLink")=>"String")
Base.propertynames(::Type{ SubnetListResult }) = collect(keys(_property_map_SubnetListResult))
Swagger.property_type(::Type{ SubnetListResult }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_SubnetListResult[name]))}
Swagger.field_name(::Type{ SubnetListResult }, property_name::Symbol) =  _property_map_SubnetListResult[property_name]

function check_required(o::SubnetListResult)
    true
end

function validate_property(::Type{ SubnetListResult }, name::Symbol, val)
end
