# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DateAfterCreation
Object to define the number of days after creation.

    DateAfterCreation(;
        daysAfterCreationGreaterThan=nothing,
    )

    - daysAfterCreationGreaterThan::Float64 : Value indicating the age in days after creation
"""
Base.@kwdef mutable struct DateAfterCreation <: OpenAPI.APIModel
    daysAfterCreationGreaterThan::Union{Nothing, Float64} = nothing

    function DateAfterCreation(daysAfterCreationGreaterThan, )
        OpenAPI.validate_property(DateAfterCreation, Symbol("daysAfterCreationGreaterThan"), daysAfterCreationGreaterThan)
        return new(daysAfterCreationGreaterThan, )
    end
end # type DateAfterCreation

const _property_types_DateAfterCreation = Dict{Symbol,String}(Symbol("daysAfterCreationGreaterThan")=>"Float64", )
OpenAPI.property_type(::Type{ DateAfterCreation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DateAfterCreation[name]))}

function check_required(o::DateAfterCreation)
    o.daysAfterCreationGreaterThan === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ DateAfterCreation }, name::Symbol, val)
    if name === Symbol("daysAfterCreationGreaterThan")
        OpenAPI.validate_param(name, "DateAfterCreation", :minimum, val, 0, false)
        OpenAPI.validate_param(name, "DateAfterCreation", :multipleOf, val, 1)
    end
end
