# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""KeyCreationTime
Storage account keys creation time.

    KeyCreationTime(;
        key1=nothing,
        key2=nothing,
    )

    - key1::ZonedDateTime
    - key2::ZonedDateTime
"""
Base.@kwdef mutable struct KeyCreationTime <: OpenAPI.APIModel
    key1::Union{Nothing, ZonedDateTime} = nothing
    key2::Union{Nothing, ZonedDateTime} = nothing

    function KeyCreationTime(key1, key2, )
        o = new(key1, key2, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type KeyCreationTime

const _property_types_KeyCreationTime = Dict{Symbol,String}(Symbol("key1")=>"ZonedDateTime", Symbol("key2")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ KeyCreationTime }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_KeyCreationTime[name]))}

function OpenAPI.check_required(o::KeyCreationTime)
    true
end

function OpenAPI.validate_properties(o::KeyCreationTime)
    OpenAPI.validate_property(KeyCreationTime, Symbol("key1"), o.key1)
    OpenAPI.validate_property(KeyCreationTime, Symbol("key2"), o.key2)
end

function OpenAPI.validate_property(::Type{ KeyCreationTime }, name::Symbol, val)

    if name === Symbol("key1")
        OpenAPI.validate_param(name, "KeyCreationTime", :format, val, "date-time")
    end

    if name === Symbol("key2")
        OpenAPI.validate_param(name, "KeyCreationTime", :format, val, "date-time")
    end
end
