# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ListServiceSasResponse
The List service SAS credentials operation response.

    ListServiceSasResponse(;
        serviceSasToken=nothing,
    )

    - serviceSasToken::String : List service SAS credentials of specific resource.
"""
Base.@kwdef mutable struct ListServiceSasResponse <: OpenAPI.APIModel
    serviceSasToken::Union{Nothing, String} = nothing

    function ListServiceSasResponse(serviceSasToken, )
        OpenAPI.validate_property(ListServiceSasResponse, Symbol("serviceSasToken"), serviceSasToken)
        return new(serviceSasToken, )
    end
end # type ListServiceSasResponse

const _property_types_ListServiceSasResponse = Dict{Symbol,String}(Symbol("serviceSasToken")=>"String", )
OpenAPI.property_type(::Type{ ListServiceSasResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListServiceSasResponse[name]))}

function check_required(o::ListServiceSasResponse)
    true
end

function OpenAPI.validate_property(::Type{ ListServiceSasResponse }, name::Symbol, val)
end
