# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""StorageAccountInternetEndpoints
The URIs that are used to perform a retrieval of a public blob, file, web or dfs object via a internet routing endpoint.

    StorageAccountInternetEndpoints(;
        blob=nothing,
        file=nothing,
        web=nothing,
        dfs=nothing,
    )

    - blob::String : Gets the blob endpoint.
    - file::String : Gets the file endpoint.
    - web::String : Gets the web endpoint.
    - dfs::String : Gets the dfs endpoint.
"""
Base.@kwdef mutable struct StorageAccountInternetEndpoints <: OpenAPI.APIModel
    blob::Union{Nothing, String} = nothing
    file::Union{Nothing, String} = nothing
    web::Union{Nothing, String} = nothing
    dfs::Union{Nothing, String} = nothing

    function StorageAccountInternetEndpoints(blob, file, web, dfs, )
        o = new(blob, file, web, dfs, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type StorageAccountInternetEndpoints

const _property_types_StorageAccountInternetEndpoints = Dict{Symbol,String}(Symbol("blob")=>"String", Symbol("file")=>"String", Symbol("web")=>"String", Symbol("dfs")=>"String", )
OpenAPI.property_type(::Type{ StorageAccountInternetEndpoints }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_StorageAccountInternetEndpoints[name]))}

function OpenAPI.check_required(o::StorageAccountInternetEndpoints)
    true
end

function OpenAPI.validate_properties(o::StorageAccountInternetEndpoints)
    OpenAPI.validate_property(StorageAccountInternetEndpoints, Symbol("blob"), o.blob)
    OpenAPI.validate_property(StorageAccountInternetEndpoints, Symbol("file"), o.file)
    OpenAPI.validate_property(StorageAccountInternetEndpoints, Symbol("web"), o.web)
    OpenAPI.validate_property(StorageAccountInternetEndpoints, Symbol("dfs"), o.dfs)
end

function OpenAPI.validate_property(::Type{ StorageAccountInternetEndpoints }, name::Symbol, val)




end
