# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PrivateLinkResource
A private link resource

    PrivateLinkResource(;
        properties=nothing,
        id=nothing,
        name=nothing,
        type=nothing,
    )

    - properties::PrivateLinkResourceProperties
    - id::String : Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
    - name::String : The name of the resource
    - type::String : The type of the resource. E.g. \&quot;Microsoft.Compute/virtualMachines\&quot; or \&quot;Microsoft.Storage/storageAccounts\&quot;
"""
Base.@kwdef mutable struct PrivateLinkResource <: OpenAPI.APIModel
    properties = nothing # spec type: Union{ Nothing, PrivateLinkResourceProperties }
    id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing

    function PrivateLinkResource(properties, id, name, type, )
        o = new(properties, id, name, type, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PrivateLinkResource

const _property_types_PrivateLinkResource = Dict{Symbol,String}(Symbol("properties")=>"PrivateLinkResourceProperties", Symbol("id")=>"String", Symbol("name")=>"String", Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ PrivateLinkResource }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PrivateLinkResource[name]))}

function OpenAPI.check_required(o::PrivateLinkResource)
    true
end

function OpenAPI.validate_properties(o::PrivateLinkResource)
    OpenAPI.validate_property(PrivateLinkResource, Symbol("properties"), o.properties)
    OpenAPI.validate_property(PrivateLinkResource, Symbol("id"), o.id)
    OpenAPI.validate_property(PrivateLinkResource, Symbol("name"), o.name)
    OpenAPI.validate_property(PrivateLinkResource, Symbol("type"), o.type)
end

function OpenAPI.validate_property(::Type{ PrivateLinkResource }, name::Symbol, val)




end
