# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

include("models/model_ContainerService.jl")
include("models/model_ContainerServiceAgentPoolProfile.jl")
include("models/model_ContainerServiceCustomProfile.jl")
include("models/model_ContainerServiceDiagnosticsProfile.jl")
include("models/model_ContainerServiceLinuxProfile.jl")
include("models/model_ContainerServiceListResult.jl")
include("models/model_ContainerServiceMasterProfile.jl")
include("models/model_ContainerServiceOrchestratorProfile.jl")
include("models/model_ContainerServiceProperties.jl")
include("models/model_ContainerServiceServicePrincipalProfile.jl")
include("models/model_ContainerServiceSshConfiguration.jl")
include("models/model_ContainerServiceSshPublicKey.jl")
include("models/model_ContainerServiceVMDiagnostics.jl")
include("models/model_ContainerServiceWindowsProfile.jl")
include("models/model_Resource.jl")
