# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct VirtualMachineScaleSetUpdatePublicIPAddressConfiguration <: SwaggerModel
    name::Any # spec type: Union{ Nothing, String } # spec name: name
    properties::Any # spec type: Union{ Nothing, VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties } # spec name: properties

    function VirtualMachineScaleSetUpdatePublicIPAddressConfiguration(;name=nothing, properties=nothing)
        o = new()
        validate_property(VirtualMachineScaleSetUpdatePublicIPAddressConfiguration, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        validate_property(VirtualMachineScaleSetUpdatePublicIPAddressConfiguration, Symbol("properties"), properties)
        setfield!(o, Symbol("properties"), properties)
        o
    end
end # type VirtualMachineScaleSetUpdatePublicIPAddressConfiguration

const _property_map_VirtualMachineScaleSetUpdatePublicIPAddressConfiguration = Dict{Symbol,Symbol}(Symbol("name")=>Symbol("name"), Symbol("properties")=>Symbol("properties"))
const _property_types_VirtualMachineScaleSetUpdatePublicIPAddressConfiguration = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("properties")=>"VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties")
Base.propertynames(::Type{ VirtualMachineScaleSetUpdatePublicIPAddressConfiguration }) = collect(keys(_property_map_VirtualMachineScaleSetUpdatePublicIPAddressConfiguration))
Swagger.property_type(::Type{ VirtualMachineScaleSetUpdatePublicIPAddressConfiguration }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_VirtualMachineScaleSetUpdatePublicIPAddressConfiguration[name]))}
Swagger.field_name(::Type{ VirtualMachineScaleSetUpdatePublicIPAddressConfiguration }, property_name::Symbol) =  _property_map_VirtualMachineScaleSetUpdatePublicIPAddressConfiguration[property_name]

function check_required(o::VirtualMachineScaleSetUpdatePublicIPAddressConfiguration)
    true
end

function validate_property(::Type{ VirtualMachineScaleSetUpdatePublicIPAddressConfiguration }, name::Symbol, val)
end
