# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type VirtualHardDisk <: SwaggerModel
    uri::Nullable{ String } # uri

    function VirtualHardDisk(;uri=nothing)
        o = new()
        set_field!(o, :uri, uri)
        o
    end
end # type VirtualHardDisk

const _name_map_VirtualHardDisk = Dict{String,Symbol}(["uri"=>:uri])
const _field_map_VirtualHardDisk = Dict{Symbol,String}([:uri=>"uri"])
Swagger.name_map(::Type{ VirtualHardDisk }) = _name_map_VirtualHardDisk
Swagger.field_map(::Type{ VirtualHardDisk }) = _field_map_VirtualHardDisk

function check_required(o::VirtualHardDisk)
    true
end

function validate_field(o::VirtualHardDisk, name::Symbol, val)
end
