# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct LogAnalyticsOutput <: SwaggerModel
    output::Any # spec type: Union{ Nothing, String } # spec name: output

    function LogAnalyticsOutput(;output=nothing)
        o = new()
        validate_property(LogAnalyticsOutput, Symbol("output"), output)
        setfield!(o, Symbol("output"), output)
        o
    end
end # type LogAnalyticsOutput

const _property_map_LogAnalyticsOutput = Dict{Symbol,Symbol}(Symbol("output")=>Symbol("output"))
const _property_types_LogAnalyticsOutput = Dict{Symbol,String}(Symbol("output")=>"String")
Base.propertynames(::Type{ LogAnalyticsOutput }) = collect(keys(_property_map_LogAnalyticsOutput))
Swagger.property_type(::Type{ LogAnalyticsOutput }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_LogAnalyticsOutput[name]))}
Swagger.field_name(::Type{ LogAnalyticsOutput }, property_name::Symbol) =  _property_map_LogAnalyticsOutput[property_name]

function check_required(o::LogAnalyticsOutput)
    true
end

function validate_property(::Type{ LogAnalyticsOutput }, name::Symbol, val)
end
