# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct VirtualMachineScaleSetPublicIPAddressConfiguration <: SwaggerModel
    name::Union{ Nothing, String } # name
    properties::Union{ Nothing, VirtualMachineScaleSetPublicIPAddressConfigurationProperties } # properties

    function VirtualMachineScaleSetPublicIPAddressConfiguration(;name=nothing, properties=nothing)
        o = new()
        set_field!(o, :name, name)
        set_field!(o, :properties, properties)
        o
    end
end # type VirtualMachineScaleSetPublicIPAddressConfiguration

const _name_map_VirtualMachineScaleSetPublicIPAddressConfiguration = Dict{String,Symbol}(["name"=>:name, "properties"=>:properties])
const _field_map_VirtualMachineScaleSetPublicIPAddressConfiguration = Dict{Symbol,String}([:name=>"name", :properties=>"properties"])
Swagger.name_map(::Type{ VirtualMachineScaleSetPublicIPAddressConfiguration }) = _name_map_VirtualMachineScaleSetPublicIPAddressConfiguration
Swagger.field_map(::Type{ VirtualMachineScaleSetPublicIPAddressConfiguration }) = _field_map_VirtualMachineScaleSetPublicIPAddressConfiguration

function check_required(o::VirtualMachineScaleSetPublicIPAddressConfiguration)
    (o.name === nothing) && (return false)
    true
end

function validate_field(o::VirtualMachineScaleSetPublicIPAddressConfiguration, name::Symbol, val)
end
