# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type RollingUpgradeStatusInfoProperties <: SwaggerModel
    policy::Nullable{ RollingUpgradePolicy } # policy
    runningStatus::Nullable{ RollingUpgradeRunningStatus } # runningStatus
    progress::Nullable{ RollingUpgradeProgressInfo } # progress
    error::Nullable{ ApiError } # error

    function RollingUpgradeStatusInfoProperties(;policy=nothing, runningStatus=nothing, progress=nothing, error=nothing)
        o = new()
        set_field!(o, :policy, policy)
        set_field!(o, :runningStatus, runningStatus)
        set_field!(o, :progress, progress)
        set_field!(o, :error, error)
        o
    end
end # type RollingUpgradeStatusInfoProperties

const _name_map_RollingUpgradeStatusInfoProperties = Dict{String,Symbol}(["policy"=>:policy, "runningStatus"=>:runningStatus, "progress"=>:progress, "error"=>:error])
const _field_map_RollingUpgradeStatusInfoProperties = Dict{Symbol,String}([:policy=>"policy", :runningStatus=>"runningStatus", :progress=>"progress", :error=>"error"])
Swagger.name_map(::Type{ RollingUpgradeStatusInfoProperties }) = _name_map_RollingUpgradeStatusInfoProperties
Swagger.field_map(::Type{ RollingUpgradeStatusInfoProperties }) = _field_map_RollingUpgradeStatusInfoProperties

function check_required(o::RollingUpgradeStatusInfoProperties)
    true
end

function validate_field(o::RollingUpgradeStatusInfoProperties, name::Symbol, val)
end
