# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct SshConfiguration <: SwaggerModel
    publicKeys::Union{ Nothing, Vector{SshPublicKey} } # publicKeys

    function SshConfiguration(;publicKeys=nothing)
        o = new()
        set_field!(o, :publicKeys, publicKeys)
        o
    end
end # type SshConfiguration

const _name_map_SshConfiguration = Dict{String,Symbol}(["publicKeys"=>:publicKeys])
const _field_map_SshConfiguration = Dict{Symbol,String}([:publicKeys=>"publicKeys"])
Swagger.name_map(::Type{ SshConfiguration }) = _name_map_SshConfiguration
Swagger.field_map(::Type{ SshConfiguration }) = _field_map_SshConfiguration

function check_required(o::SshConfiguration)
    true
end

function validate_field(o::SshConfiguration, name::Symbol, val)
end
