# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type ApplicationGatewayBackendHealthPool <: SwaggerModel
    backendAddressPool::Nullable{ ApplicationGatewayBackendAddressPool } # backendAddressPool
    backendHttpSettingsCollection::Nullable{ Vector{ApplicationGatewayBackendHealthHttpSettings} } # backendHttpSettingsCollection

    function ApplicationGatewayBackendHealthPool(;backendAddressPool=nothing, backendHttpSettingsCollection=nothing)
        o = new()
        set_field!(o, :backendAddressPool, backendAddressPool)
        set_field!(o, :backendHttpSettingsCollection, backendHttpSettingsCollection)
        o
    end
end # type ApplicationGatewayBackendHealthPool

const _name_map_ApplicationGatewayBackendHealthPool = Dict{String,Symbol}(["backendAddressPool"=>:backendAddressPool, "backendHttpSettingsCollection"=>:backendHttpSettingsCollection])
const _field_map_ApplicationGatewayBackendHealthPool = Dict{Symbol,String}([:backendAddressPool=>"backendAddressPool", :backendHttpSettingsCollection=>"backendHttpSettingsCollection"])
Swagger.name_map(::Type{ ApplicationGatewayBackendHealthPool }) = _name_map_ApplicationGatewayBackendHealthPool
Swagger.field_map(::Type{ ApplicationGatewayBackendHealthPool }) = _field_map_ApplicationGatewayBackendHealthPool

function check_required(o::ApplicationGatewayBackendHealthPool)
    true
end

function validate_field(o::ApplicationGatewayBackendHealthPool, name::Symbol, val)
end
