# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct ApplicationGatewayFirewallRuleSet <: SwaggerModel
    id::Any # spec type: Union{ Nothing, String } # spec name: id
    name::Any # spec type: Union{ Nothing, String } # spec name: name
    type::Any # spec type: Union{ Nothing, String } # spec name: type
    location::Any # spec type: Union{ Nothing, String } # spec name: location
    tags::Any # spec type: Union{ Nothing, Dict{String, String} } # spec name: tags

    function ApplicationGatewayFirewallRuleSet(;id=nothing, name=nothing, type=nothing, location=nothing, tags=nothing)
        o = new()
        validate_property(ApplicationGatewayFirewallRuleSet, Symbol("id"), id)
        setfield!(o, Symbol("id"), id)
        validate_property(ApplicationGatewayFirewallRuleSet, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        validate_property(ApplicationGatewayFirewallRuleSet, Symbol("type"), type)
        setfield!(o, Symbol("type"), type)
        validate_property(ApplicationGatewayFirewallRuleSet, Symbol("location"), location)
        setfield!(o, Symbol("location"), location)
        validate_property(ApplicationGatewayFirewallRuleSet, Symbol("tags"), tags)
        setfield!(o, Symbol("tags"), tags)
        o
    end
end # type ApplicationGatewayFirewallRuleSet

const _property_map_ApplicationGatewayFirewallRuleSet = Dict{Symbol,Symbol}(Symbol("id")=>Symbol("id"), Symbol("name")=>Symbol("name"), Symbol("type")=>Symbol("type"), Symbol("location")=>Symbol("location"), Symbol("tags")=>Symbol("tags"))
const _property_types_ApplicationGatewayFirewallRuleSet = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", Symbol("type")=>"String", Symbol("location")=>"String", Symbol("tags")=>"Dict{String, String}")
Base.propertynames(::Type{ ApplicationGatewayFirewallRuleSet }) = collect(keys(_property_map_ApplicationGatewayFirewallRuleSet))
Swagger.property_type(::Type{ ApplicationGatewayFirewallRuleSet }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_ApplicationGatewayFirewallRuleSet[name]))}
Swagger.field_name(::Type{ ApplicationGatewayFirewallRuleSet }, property_name::Symbol) =  _property_map_ApplicationGatewayFirewallRuleSet[property_name]

function check_required(o::ApplicationGatewayFirewallRuleSet)
    true
end

function validate_property(::Type{ ApplicationGatewayFirewallRuleSet }, name::Symbol, val)
end
