# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""LoadBalancingRule
A load balancing rule for a load balancer.

    LoadBalancingRule(;
        properties=nothing,
        name=nothing,
        etag=nothing,
        type=nothing,
        id=nothing,
    )

    - properties::LoadBalancingRulePropertiesFormat
    - name::String : The name of the resource that is unique within the set of load balancing rules used by the load balancer. This name can be used to access the resource.
    - etag::String : A unique read-only string that changes whenever the resource is updated.
    - type::String : Type of the resource.
    - id::String : Resource ID.
"""
Base.@kwdef mutable struct LoadBalancingRule <: OpenAPI.APIModel
    properties = nothing # spec type: Union{ Nothing, LoadBalancingRulePropertiesFormat }
    name::Union{Nothing, String} = nothing
    etag::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing
    id::Union{Nothing, String} = nothing

    function LoadBalancingRule(properties, name, etag, type, id, )
        OpenAPI.validate_property(LoadBalancingRule, Symbol("properties"), properties)
        OpenAPI.validate_property(LoadBalancingRule, Symbol("name"), name)
        OpenAPI.validate_property(LoadBalancingRule, Symbol("etag"), etag)
        OpenAPI.validate_property(LoadBalancingRule, Symbol("type"), type)
        OpenAPI.validate_property(LoadBalancingRule, Symbol("id"), id)
        return new(properties, name, etag, type, id, )
    end
end # type LoadBalancingRule

const _property_types_LoadBalancingRule = Dict{Symbol,String}(Symbol("properties")=>"LoadBalancingRulePropertiesFormat", Symbol("name")=>"String", Symbol("etag")=>"String", Symbol("type")=>"String", Symbol("id")=>"String", )
OpenAPI.property_type(::Type{ LoadBalancingRule }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_LoadBalancingRule[name]))}

function check_required(o::LoadBalancingRule)
    true
end

function OpenAPI.validate_property(::Type{ LoadBalancingRule }, name::Symbol, val)
end
