# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DdosSettings
Contains the DDoS protection settings of the public IP.

    DdosSettings(;
        protectionMode=nothing,
        ddosProtectionPlan=nothing,
    )

    - protectionMode::String : The DDoS protection mode of the public IP
    - ddosProtectionPlan::SubResource
"""
Base.@kwdef mutable struct DdosSettings <: OpenAPI.APIModel
    protectionMode::Union{Nothing, String} = nothing
    ddosProtectionPlan = nothing # spec type: Union{ Nothing, SubResource }

    function DdosSettings(protectionMode, ddosProtectionPlan, )
        o = new(protectionMode, ddosProtectionPlan, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DdosSettings

const _property_types_DdosSettings = Dict{Symbol,String}(Symbol("protectionMode")=>"String", Symbol("ddosProtectionPlan")=>"SubResource", )
OpenAPI.property_type(::Type{ DdosSettings }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DdosSettings[name]))}

function OpenAPI.check_required(o::DdosSettings)
    true
end

function OpenAPI.validate_properties(o::DdosSettings)
    OpenAPI.validate_property(DdosSettings, Symbol("protectionMode"), o.protectionMode)
    OpenAPI.validate_property(DdosSettings, Symbol("ddosProtectionPlan"), o.ddosProtectionPlan)
end

function OpenAPI.validate_property(::Type{ DdosSettings }, name::Symbol, val)

    if name === Symbol("protectionMode")
        OpenAPI.validate_param(name, "DdosSettings", :enum, val, ["VirtualNetworkInherited", "Enabled", "Disabled"])
    end


end
