# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DedicatedHostAvailableCapacity
Dedicated host unutilized capacity.

    DedicatedHostAvailableCapacity(;
        allocatableVMs=nothing,
    )

    - allocatableVMs::Vector{DedicatedHostAllocatableVM} : The unutilized capacity of the dedicated host represented in terms of each VM size that is allowed to be deployed to the dedicated host.
"""
Base.@kwdef mutable struct DedicatedHostAvailableCapacity <: OpenAPI.APIModel
    allocatableVMs::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{DedicatedHostAllocatableVM} }

    function DedicatedHostAvailableCapacity(allocatableVMs, )
        OpenAPI.validate_property(DedicatedHostAvailableCapacity, Symbol("allocatableVMs"), allocatableVMs)
        return new(allocatableVMs, )
    end
end # type DedicatedHostAvailableCapacity

const _property_types_DedicatedHostAvailableCapacity = Dict{Symbol,String}(Symbol("allocatableVMs")=>"Vector{DedicatedHostAllocatableVM}", )
OpenAPI.property_type(::Type{ DedicatedHostAvailableCapacity }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DedicatedHostAvailableCapacity[name]))}

function check_required(o::DedicatedHostAvailableCapacity)
    true
end

function OpenAPI.validate_property(::Type{ DedicatedHostAvailableCapacity }, name::Symbol, val)
end
