# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties
Describes a virtual machines scale set IP Configuration&#39;s PublicIPAddress configuration

    VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties(;
        idleTimeoutInMinutes=nothing,
        dnsSettings=nothing,
    )

    - idleTimeoutInMinutes::Int64 : The idle timeout of the public IP address.
    - dnsSettings::VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings
"""
Base.@kwdef mutable struct VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties <: OpenAPI.APIModel
    idleTimeoutInMinutes::Union{Nothing, Int64} = nothing
    dnsSettings = nothing # spec type: Union{ Nothing, VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings }

    function VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties(idleTimeoutInMinutes, dnsSettings, )
        OpenAPI.validate_property(VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties, Symbol("idleTimeoutInMinutes"), idleTimeoutInMinutes)
        OpenAPI.validate_property(VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties, Symbol("dnsSettings"), dnsSettings)
        return new(idleTimeoutInMinutes, dnsSettings, )
    end
end # type VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties

const _property_types_VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties = Dict{Symbol,String}(Symbol("idleTimeoutInMinutes")=>"Int64", Symbol("dnsSettings")=>"VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings", )
OpenAPI.property_type(::Type{ VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties[name]))}

function check_required(o::VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties)
    true
end

function OpenAPI.validate_property(::Type{ VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties }, name::Symbol, val)
    if name === Symbol("idleTimeoutInMinutes")
        OpenAPI.validate_param(name, "VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties", :format, val, "int32")
    end
end
