# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""VirtualMachineScaleSetUpdatePublicIPAddressConfiguration
Describes a virtual machines scale set IP Configuration&#39;s PublicIPAddress configuration

    VirtualMachineScaleSetUpdatePublicIPAddressConfiguration(;
        name=nothing,
        properties=nothing,
    )

    - name::String : The publicIP address configuration name.
    - properties::VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties
"""
Base.@kwdef mutable struct VirtualMachineScaleSetUpdatePublicIPAddressConfiguration <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    properties = nothing # spec type: Union{ Nothing, VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties }

    function VirtualMachineScaleSetUpdatePublicIPAddressConfiguration(name, properties, )
        o = new(name, properties, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type VirtualMachineScaleSetUpdatePublicIPAddressConfiguration

const _property_types_VirtualMachineScaleSetUpdatePublicIPAddressConfiguration = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("properties")=>"VirtualMachineScaleSetUpdatePublicIPAddressConfigurationProperties", )
OpenAPI.property_type(::Type{ VirtualMachineScaleSetUpdatePublicIPAddressConfiguration }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_VirtualMachineScaleSetUpdatePublicIPAddressConfiguration[name]))}

function OpenAPI.check_required(o::VirtualMachineScaleSetUpdatePublicIPAddressConfiguration)
    true
end

function OpenAPI.validate_properties(o::VirtualMachineScaleSetUpdatePublicIPAddressConfiguration)
    OpenAPI.validate_property(VirtualMachineScaleSetUpdatePublicIPAddressConfiguration, Symbol("name"), o.name)
    OpenAPI.validate_property(VirtualMachineScaleSetUpdatePublicIPAddressConfiguration, Symbol("properties"), o.properties)
end

function OpenAPI.validate_property(::Type{ VirtualMachineScaleSetUpdatePublicIPAddressConfiguration }, name::Symbol, val)


end
