# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RecoveryWalkResponse
Response after calling a manual recovery walk

    RecoveryWalkResponse(;
        walkPerformed=nothing,
        nextPlatformUpdateDomain=nothing,
    )

    - walkPerformed::Bool : Whether the recovery walk was performed
    - nextPlatformUpdateDomain::Int64 : The next update domain that needs to be walked. Null means walk spanning all update domains has been completed
"""
Base.@kwdef mutable struct RecoveryWalkResponse <: OpenAPI.APIModel
    walkPerformed::Union{Nothing, Bool} = nothing
    nextPlatformUpdateDomain::Union{Nothing, Int64} = nothing

    function RecoveryWalkResponse(walkPerformed, nextPlatformUpdateDomain, )
        OpenAPI.validate_property(RecoveryWalkResponse, Symbol("walkPerformed"), walkPerformed)
        OpenAPI.validate_property(RecoveryWalkResponse, Symbol("nextPlatformUpdateDomain"), nextPlatformUpdateDomain)
        return new(walkPerformed, nextPlatformUpdateDomain, )
    end
end # type RecoveryWalkResponse

const _property_types_RecoveryWalkResponse = Dict{Symbol,String}(Symbol("walkPerformed")=>"Bool", Symbol("nextPlatformUpdateDomain")=>"Int64", )
OpenAPI.property_type(::Type{ RecoveryWalkResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RecoveryWalkResponse[name]))}

function check_required(o::RecoveryWalkResponse)
    true
end

function OpenAPI.validate_property(::Type{ RecoveryWalkResponse }, name::Symbol, val)
end
