# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""VirtualMachineScaleSetInstanceViewStatusesSummary
Instance view statuses summary for virtual machines of a virtual machine scale set.

    VirtualMachineScaleSetInstanceViewStatusesSummary(;
        statusesSummary=nothing,
    )

    - statusesSummary::Vector{VirtualMachineStatusCodeCount} : The extensions information.
"""
Base.@kwdef mutable struct VirtualMachineScaleSetInstanceViewStatusesSummary <: OpenAPI.APIModel
    statusesSummary::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{VirtualMachineStatusCodeCount} }

    function VirtualMachineScaleSetInstanceViewStatusesSummary(statusesSummary, )
        OpenAPI.validate_property(VirtualMachineScaleSetInstanceViewStatusesSummary, Symbol("statusesSummary"), statusesSummary)
        return new(statusesSummary, )
    end
end # type VirtualMachineScaleSetInstanceViewStatusesSummary

const _property_types_VirtualMachineScaleSetInstanceViewStatusesSummary = Dict{Symbol,String}(Symbol("statusesSummary")=>"Vector{VirtualMachineStatusCodeCount}", )
OpenAPI.property_type(::Type{ VirtualMachineScaleSetInstanceViewStatusesSummary }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_VirtualMachineScaleSetInstanceViewStatusesSummary[name]))}

function check_required(o::VirtualMachineScaleSetInstanceViewStatusesSummary)
    true
end

function OpenAPI.validate_property(::Type{ VirtualMachineScaleSetInstanceViewStatusesSummary }, name::Symbol, val)
end
