# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RestorePointCollectionListResult
The List restore point collection operation response.

    RestorePointCollectionListResult(;
        value=nothing,
        nextLink=nothing,
    )

    - value::Vector{RestorePointCollection} : Gets the list of restore point collections.
    - nextLink::String : The uri to fetch the next page of RestorePointCollections. Call ListNext() with this to fetch the next page of RestorePointCollections
"""
Base.@kwdef mutable struct RestorePointCollectionListResult <: OpenAPI.APIModel
    value::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{RestorePointCollection} }
    nextLink::Union{Nothing, String} = nothing

    function RestorePointCollectionListResult(value, nextLink, )
        o = new(value, nextLink, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type RestorePointCollectionListResult

const _property_types_RestorePointCollectionListResult = Dict{Symbol,String}(Symbol("value")=>"Vector{RestorePointCollection}", Symbol("nextLink")=>"String", )
OpenAPI.property_type(::Type{ RestorePointCollectionListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RestorePointCollectionListResult[name]))}

function OpenAPI.check_required(o::RestorePointCollectionListResult)
    true
end

function OpenAPI.validate_properties(o::RestorePointCollectionListResult)
    OpenAPI.validate_property(RestorePointCollectionListResult, Symbol("value"), o.value)
    OpenAPI.validate_property(RestorePointCollectionListResult, Symbol("nextLink"), o.nextLink)
end

function OpenAPI.validate_property(::Type{ RestorePointCollectionListResult }, name::Symbol, val)


end
