# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""KeyVaultKeyReference
Describes a reference to Key Vault Key

    KeyVaultKeyReference(;
        keyUrl=nothing,
        sourceVault=nothing,
    )

    - keyUrl::String : The URL referencing a key encryption key in Key Vault.
    - sourceVault::SubResource
"""
Base.@kwdef mutable struct KeyVaultKeyReference <: OpenAPI.APIModel
    keyUrl::Union{Nothing, String} = nothing
    sourceVault = nothing # spec type: Union{ Nothing, SubResource }

    function KeyVaultKeyReference(keyUrl, sourceVault, )
        OpenAPI.validate_property(KeyVaultKeyReference, Symbol("keyUrl"), keyUrl)
        OpenAPI.validate_property(KeyVaultKeyReference, Symbol("sourceVault"), sourceVault)
        return new(keyUrl, sourceVault, )
    end
end # type KeyVaultKeyReference

const _property_types_KeyVaultKeyReference = Dict{Symbol,String}(Symbol("keyUrl")=>"String", Symbol("sourceVault")=>"SubResource", )
OpenAPI.property_type(::Type{ KeyVaultKeyReference }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_KeyVaultKeyReference[name]))}

function check_required(o::KeyVaultKeyReference)
    o.keyUrl === nothing && (return false)
    o.sourceVault === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ KeyVaultKeyReference }, name::Symbol, val)
end
