# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct FirewallRuleProperties <: SwaggerModel
    startIpAddress::Union{ Nothing, String } # startIpAddress
    endIpAddress::Union{ Nothing, String } # endIpAddress

    function FirewallRuleProperties(;startIpAddress=nothing, endIpAddress=nothing)
        o = new()
        set_field!(o, :startIpAddress, startIpAddress)
        set_field!(o, :endIpAddress, endIpAddress)
        o
    end
end # type FirewallRuleProperties

const _name_map_FirewallRuleProperties = Dict{String,Symbol}(["startIpAddress"=>:startIpAddress, "endIpAddress"=>:endIpAddress])
const _field_map_FirewallRuleProperties = Dict{Symbol,String}([:startIpAddress=>"startIpAddress", :endIpAddress=>"endIpAddress"])
Swagger.name_map(::Type{ FirewallRuleProperties }) = _name_map_FirewallRuleProperties
Swagger.field_map(::Type{ FirewallRuleProperties }) = _field_map_FirewallRuleProperties

function check_required(o::FirewallRuleProperties)
    (o.startIpAddress === nothing) && (return false)
    (o.endIpAddress === nothing) && (return false)
    true
end

function validate_field(o::FirewallRuleProperties, name::Symbol, val)
end
