# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ShareInfoElement

    ShareInfoElement(;
        vmUri=nothing,
    )

    - vmUri::String : A relative URI containing the ID of the VM that has the disk attached.
"""
Base.@kwdef mutable struct ShareInfoElement <: OpenAPI.APIModel
    vmUri::Union{Nothing, String} = nothing

    function ShareInfoElement(vmUri, )
        OpenAPI.validate_property(ShareInfoElement, Symbol("vmUri"), vmUri)
        return new(vmUri, )
    end
end # type ShareInfoElement

const _property_types_ShareInfoElement = Dict{Symbol,String}(Symbol("vmUri")=>"String", )
OpenAPI.property_type(::Type{ ShareInfoElement }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ShareInfoElement[name]))}

function check_required(o::ShareInfoElement)
    true
end

function OpenAPI.validate_property(::Type{ ShareInfoElement }, name::Symbol, val)
end
