# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct UsagesListResult <: SwaggerModel
    value::Any # spec type: Union{ Nothing, Vector{Usage} } # spec name: value
    nextLink::Any # spec type: Union{ Nothing, String } # spec name: nextLink

    function UsagesListResult(;value=nothing, nextLink=nothing)
        o = new()
        validate_property(UsagesListResult, Symbol("value"), value)
        setfield!(o, Symbol("value"), value)
        validate_property(UsagesListResult, Symbol("nextLink"), nextLink)
        setfield!(o, Symbol("nextLink"), nextLink)
        o
    end
end # type UsagesListResult

const _property_map_UsagesListResult = Dict{Symbol,Symbol}(Symbol("value")=>Symbol("value"), Symbol("nextLink")=>Symbol("nextLink"))
const _property_types_UsagesListResult = Dict{Symbol,String}(Symbol("value")=>"Vector{Usage}", Symbol("nextLink")=>"String")
Base.propertynames(::Type{ UsagesListResult }) = collect(keys(_property_map_UsagesListResult))
Swagger.property_type(::Type{ UsagesListResult }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_UsagesListResult[name]))}
Swagger.field_name(::Type{ UsagesListResult }, property_name::Symbol) =  _property_map_UsagesListResult[property_name]

function check_required(o::UsagesListResult)
    true
end

function validate_property(::Type{ UsagesListResult }, name::Symbol, val)
end
