# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

module NetworkManagementClient

using Random
using Dates
using HTTP
using Swagger
import Swagger: set_field!, get_field, isset_field, validate_field, SwaggerApi, SwaggerModel
import Base: convert

include("modelincludes.jl")


# export models
export convert, AzureAsyncOperationResult
export convert, Error
export convert, ErrorDetails
export convert, Resource
export convert, SubResource

# export operations
export convert

export check_required, set_field!, get_field, isset_field, convert

end
