# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RouteFilterListResult
Response for the ListRouteFilters API service call.

    RouteFilterListResult(;
        value=nothing,
        nextLink=nothing,
    )

    - value::Vector{RouteFilter} : A list of route filters in a resource group.
    - nextLink::String : The URL to get the next set of results.
"""
Base.@kwdef mutable struct RouteFilterListResult <: OpenAPI.APIModel
    value::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{RouteFilter} }
    nextLink::Union{Nothing, String} = nothing

    function RouteFilterListResult(value, nextLink, )
        o = new(value, nextLink, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type RouteFilterListResult

const _property_types_RouteFilterListResult = Dict{Symbol,String}(Symbol("value")=>"Vector{RouteFilter}", Symbol("nextLink")=>"String", )
OpenAPI.property_type(::Type{ RouteFilterListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RouteFilterListResult[name]))}

function OpenAPI.check_required(o::RouteFilterListResult)
    true
end

function OpenAPI.validate_properties(o::RouteFilterListResult)
    OpenAPI.validate_property(RouteFilterListResult, Symbol("value"), o.value)
    OpenAPI.validate_property(RouteFilterListResult, Symbol("nextLink"), o.nextLink)
end

function OpenAPI.validate_property(::Type{ RouteFilterListResult }, name::Symbol, val)


end
