# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PatchRouteFilter
Route Filter Resource.

    PatchRouteFilter(;
        properties=nothing,
        name=nothing,
        etag=nothing,
        type=nothing,
        tags=nothing,
        id=nothing,
    )

    - properties::RouteFilterPropertiesFormat
    - name::String : The name of the resource that is unique within a resource group. This name can be used to access the resource.
    - etag::String : A unique read-only string that changes whenever the resource is updated.
    - type::String : Resource type.
    - tags::Dict{String, String} : Resource tags.
    - id::String : Resource ID.
"""
Base.@kwdef mutable struct PatchRouteFilter <: OpenAPI.APIModel
    properties = nothing # spec type: Union{ Nothing, RouteFilterPropertiesFormat }
    name::Union{Nothing, String} = nothing
    etag::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing
    tags::Union{Nothing, Dict{String, String}} = nothing
    id::Union{Nothing, String} = nothing

    function PatchRouteFilter(properties, name, etag, type, tags, id, )
        o = new(properties, name, etag, type, tags, id, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PatchRouteFilter

const _property_types_PatchRouteFilter = Dict{Symbol,String}(Symbol("properties")=>"RouteFilterPropertiesFormat", Symbol("name")=>"String", Symbol("etag")=>"String", Symbol("type")=>"String", Symbol("tags")=>"Dict{String, String}", Symbol("id")=>"String", )
OpenAPI.property_type(::Type{ PatchRouteFilter }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PatchRouteFilter[name]))}

function OpenAPI.check_required(o::PatchRouteFilter)
    true
end

function OpenAPI.validate_properties(o::PatchRouteFilter)
    OpenAPI.validate_property(PatchRouteFilter, Symbol("properties"), o.properties)
    OpenAPI.validate_property(PatchRouteFilter, Symbol("name"), o.name)
    OpenAPI.validate_property(PatchRouteFilter, Symbol("etag"), o.etag)
    OpenAPI.validate_property(PatchRouteFilter, Symbol("type"), o.type)
    OpenAPI.validate_property(PatchRouteFilter, Symbol("tags"), o.tags)
    OpenAPI.validate_property(PatchRouteFilter, Symbol("id"), o.id)
end

function OpenAPI.validate_property(::Type{ PatchRouteFilter }, name::Symbol, val)






end
