# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct IPConfigurationProfile <: SwaggerModel
    id::Any # spec type: Union{ Nothing, String } # spec name: id

    function IPConfigurationProfile(;id=nothing)
        o = new()
        validate_property(IPConfigurationProfile, Symbol("id"), id)
        setfield!(o, Symbol("id"), id)
        o
    end
end # type IPConfigurationProfile

const _property_map_IPConfigurationProfile = Dict{Symbol,Symbol}(Symbol("id")=>Symbol("id"))
const _property_types_IPConfigurationProfile = Dict{Symbol,String}(Symbol("id")=>"String")
Base.propertynames(::Type{ IPConfigurationProfile }) = collect(keys(_property_map_IPConfigurationProfile))
Swagger.property_type(::Type{ IPConfigurationProfile }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IPConfigurationProfile[name]))}
Swagger.field_name(::Type{ IPConfigurationProfile }, property_name::Symbol) =  _property_map_IPConfigurationProfile[property_name]

function check_required(o::IPConfigurationProfile)
    true
end

function validate_property(::Type{ IPConfigurationProfile }, name::Symbol, val)
end
