# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct BgpPeerStatusListResult <: SwaggerModel
    value::Union{ Nothing, Vector{BgpPeerStatus} } # value

    function BgpPeerStatusListResult(;value=nothing)
        o = new()
        set_field!(o, :value, value)
        o
    end
end # type BgpPeerStatusListResult

const _name_map_BgpPeerStatusListResult = Dict{String,Symbol}(["value"=>:value])
const _field_map_BgpPeerStatusListResult = Dict{Symbol,String}([:value=>"value"])
Swagger.name_map(::Type{ BgpPeerStatusListResult }) = _name_map_BgpPeerStatusListResult
Swagger.field_map(::Type{ BgpPeerStatusListResult }) = _field_map_BgpPeerStatusListResult

function check_required(o::BgpPeerStatusListResult)
    true
end

function validate_field(o::BgpPeerStatusListResult, name::Symbol, val)
end
